var gv_mlang_en_US = { 
 "10년":"10Years",
 "10년":"10Years",
 "1년":"1Year",
 "1년":"1Year",
 "1단":"1 Step",
 "1단":"1 Step",
 "2단":"2 Step",
 "2단":"2 Step",
 "3년":"3Years",
 "3년":"3Years",
 "5년":"5Years",
 "5년":"5Years",
 "Conditional Approval":"Conditional Approval",
 "Conditional Approval":"Conditional Approval",
 "KDB 사전협의":"KDB Consultation",
 "KDB 사전협의":"KDB Consultation",
 "KDB사전협의":"KDB Consultation",
 "KDB사전협의":"KDB Consultation",
 "RISK심의":"RISK Deliberation",
 "RISK심의":"RISK Deliberation",
 "Reset":"Reset",
 "Reset":"Reset",
 "Risk심의함":"Risk Deliberation",
 "Risk심의함":"Risk Deliberation",
 "TDMS이관":"TDMS Migration",
 "TDMS이관":"TDMS Migration",
 "[시작일]":"[Start Date]",
 "[시작일]":"[Start Date]",
 "[종료일]":"[End Date]",
 "[종료일]":"[End Date]",
 "간사":"Incharge",
 "간사":"Incharge",
 "개인결재선 목록":"Saved Approvers List",
 "개인결재선 목록":"Saved Approvers List",
 "개인결재선 저장":"Save Approvers",
 "개인결재선 저장":"Save Approvers",
 "개인결재선저장":"Save Approvers",
 "개인결재선저장":"Save Approvers",
 "결재":"Approval",
 "결재":"Approval",
 "결재 문서":"Approval Document",
 "결재 문서":"Approval Document",
 "결재 취소":"Cancel Approvals",
 "결재 취소":"Cancel Approvals",
 "결재(확인)일시":"Conf.Date",
 "결재(확인)일시":"Conf.Date",
 "결재ID":"ID",
 "결재ID":"ID",
 "결재▼":"Approval▼",
 "결재▼":"Approval▼",
 "결재관리":"Approval Management",
 "결재관리":"Approval Management",
 "결재단계":"Step Info",
 "결재단계":"Step Info",
 "결재라인코드":"Approvers Code",
 "결재라인코드":"Approvers Code",
 "결재명":"Approval name",
 "결재명":"Approval name",
 "결재문서":"Approval Document",
 "결재문서":"Approval Document",
 "결재문서관리":"Doc Approving Mgmt",
 "결재문서관리":"Doc Approving Mgmt",
 "결재문서보기":"Approval Document View",
 "결재문서보기":"Approval Document View",
 "결재문서상태":"Doc. Status",
 "결재문서상태":"Doc. Status",
 "결재반려":"Approval rejection",
 "결재반려":"Approval rejection",
 "결재방법":"Approval Type",
 "결재방법":"Approval Type",
 "결재보기":"Approval View",
 "결재보기":"Approval View",
 "결재상태":"Approval Status",
 "결재상태":"Approval Status",
 "결재상태보기":"Approval Status View",
 "결재상태보기":"Approval Status View",
 "결재선":"Approvers",
 "결재선":"Approvers",
 "결재선 출력여부":"Print Approvers Y/N",
 "결재선 출력여부":"Print Approvers Y/N",
 "결재선명":"Name",
 "결재선명":"Name",
 "결재선변경":"Approvers",
 "결재선변경":"Approvers",
 "결재선설명":"Description",
 "결재선설명":"Description",
 "결재선정보":"Approvers",
 "결재선정보":"Approvers",
 "결재선지정":"Approvers",
 "결재선지정":"Approvers",
 "결재순번":"Approval Order",
 "결재순번":"Approval Order",
 "결재승인":"Approval",
 "결재승인":"Approval",
 "결재없음":"No approval",
 "결재없음":"No approval",
 "결재연계ID":"Interface ID",
 "결재연계ID":"Interface ID",
 "결재요청 취소":"Approval request cancelled",
 "결재요청 취소":"Approval request cancelled",
 "결재요청취소":"Approval request cancelled",
 "결재요청취소":"Approval request cancelled",
 "결재유형":"Approval Type",
 "결재유형":"Approval Type",
 "결재의견":"Opinion",
 "결재의견":"Opinion",
 "결재의견/포스트 잇":"Opinion/Post-It",
 "결재의견/포스트 잇":"Opinion/Post-It",
 "결재의견자":"Opinoioner",
 "결재의견자":"Opinoioner",
 "결재일시":"Approval Date",
 "결재일시":"Approval Date",
 "결재일자":"Approval Date",
 "결재일자":"Approval Date",
 "결재자":"Approver",
 "결재자":"Approver",
 "결재자 상태 수정":"Change Approver Status",
 "결재자 상태 수정":"Change Approver Status",
 "결재자 의견":"Opinion",
 "결재자 의견":"Opinion",
 "결재자 정보":"Approvers",
 "결재자 정보":"Approvers",
 "결재자ID":"User ID",
 "결재자ID":"User ID",
 "결재자이름":"Name",
 "결재자이름":"Name",
 "결재자지정":"Approver",
 "결재자지정":"Approver",
 "결재정보":"Approval Info",
 "결재정보":"Approval Info",
 "결재정보조회":"Approval Info",
 "결재정보조회":"Approval Info",
 "결재조건":"Approval Condition",
 "결재조건":"Approval Condition",
 "결재진행정보":"Approval Status Info",
 "결재진행정보":"Approval Status Info",
 "결재프로그램":"Approval Program",
 "결재프로그램":"Approval Program",
 "결재프로세스":"Approval Process",
 "결재프로세스":"Approval Process",
 "공시해당":"Disclosure",
 "공시해당":"Disclosure",
 "공용 수신처 목록":"Official Recipient List",
 "공용 수신처 목록":"Official Recipient List",
 "공용 수신처 이름":"Official Recipient Name",
 "공용 수신처 이름":"Official Recipient Name",
 "공용 수신처 쿼리":"Official Recipient Query",
 "공용 수신처 쿼리":"Official Recipient Query",
 "공용그룹관리":"Common Group Mgmt",
 "공용그룹관리":"Common Group Mgmt",
 "공통그룹목록":"Common Group List",
 "공통그룹목록":"Common Group List",
 "구분":"Class",
 "구분":"Class",
 "그룹명":"Group name",
 "그룹명":"Group name",
 "기본결재선":"Base Approvers",
 "기본결재선":"Base Approvers",
 "기본결재선 상세":"Detail",
 "기본결재선 상세":"Detail",
 "기본결재선관리":"Base Approvers Mgmt.",
 "기본결재선관리":"Base Approvers Mgmt.",
 "기본결재선목록":"Base Approvers List",
 "기본결재선목록":"Base Approvers List",
 "기안":"Draft",
 "기안":"Draft",
 "기안 양식":"Draft Form",
 "기안 양식":"Draft Form",
 "기안부서":"Draft Dept",
 "기안부서":"Draft Dept",
 "기안완료":"Draft Completed",
 "기안완료":"Draft Completed",
 "기안일":"Draft Date",
 "기안일":"Draft Date",
 "기안일자":"Date",
 "기안일자":"Date",
 "기안자":"Drafter",
 "기안자":"Drafter",
 "기안자전결":"Drafter's Discretions",
 "기안자전결":"Drafter's Discretions",
 "기안품의 여부":"Approval Request Flag",
 "기안품의 여부":"Approval Request Flag",
 "기안함":"Draft Box",
 "기안함":"Draft Box",
 "다운로드":"Download",
 "다운로드":"Download",
 "닫기":"Close",
 "닫기":"Close",
 "담당자":"Registrant",
 "담당자":"Registrant",
 "담당자 의견사항":"Charger Comment",
 "담당자 의견사항":"Charger Comment",
 "대결기간":"Issue Date",
 "대결기간":"Issue Date",
 "대결여부":"Proxy Y/N",
 "대결여부":"Proxy Y/N",
 "대결완료":"Completion of approval by vicarious authority",
 "대결완료":"Completion of approval by vicarious authority",
 "대결자 지정":"Set Proxy Approver",
 "대결자 지정":"Set Proxy Approver",
 "대결함":"Box for approval by vicarious authority",
 "대결함":"Box for approval by vicarious authority",
 "대리결재 (可)":"Proxy Approval(Yes)",
 "대리결재 (可)":"Proxy Approval(Yes)",
 "대리결재 (不)":"Proxy Approval(No)",
 "대리결재 (不)":"Proxy Approval(No)",
 "대리결재 사유":"Reason",
 "대리결재 사유":"Reason",
 "대리결재사유":"Reason of Proxy Approve",
 "대리결재사유":"Reason of Proxy Approve",
 "대리결재자":"Proxy Approver",
 "대리결재자":"Proxy Approver",
 "등록일":"Issue Date",
 "등록일":"Issue Date",
 "등록일시":"Registration Date",
 "등록일시":"Registration Date",
 "등록자":"Creator",
 "등록자":"Creator",
 "로그인 화면":"Login Screen",
 "로그인 화면":"Login Screen",
 "로그인ID":"Login ID",
 "로그인ID":"Login ID",
 "로그인일시":"Log date",
 "로그인일시":"Log date",
 "리스크심의":"Risk Deliberation",
 "리스크심의":"Risk Deliberation",
 "모바일결재여부":"Mobile Sign Y/N",
 "모바일결재여부":"Mobile Sign Y/N",
 "목록":"List",
 "목록":"List",
 "무":"No",
 "무":"No",
 "문서 번호":"Doc. No",
 "문서 번호":"Doc. No",
 "문서번호":"Doc. No.",
 "문서번호":"Doc. No.",
 "문서보안":"Doc. Security",
 "문서보안":"Doc. Security",
 "문서상태":"Doc. Status",
 "문서상태":"Doc. Status",
 "문서정보":"Doc. Info",
 "문서정보":"Doc. Info",
 "문서정보수정":"Doc.Info Modify",
 "문서정보수정":"Doc.Info Modify",
 "문서제목":"Doc. Title",
 "문서제목":"Doc. Title",
 "문서첨부":"Doc Attachment",
 "문서첨부":"Doc Attachment",
 "문서함":"Doc. Box",
 "문서함":"Doc. Box",
 "문서함종류":"Doc. Box",
 "문서함종류":"Doc. Box",
 "문서형식정보":"Doc Form Info",
 "문서형식정보":"Doc Form Info",
 "미결함":"Pending box",
 "미결함":"Pending box",
 "미결함 목록":"미결함 목록",
 "미결함 목록":"미결함 목록",
 "미리보기":"Preview",
 "미리보기":"Preview",
 "미승인":"Unapproved",
 "미승인":"Unapproved",
 "반려":"Reject",
 "반려":"Reject",
 "반려/회수":"Reject/Withdraw Box",
 "반려/회수":"Reject/Withdraw Box",
 "반려/회수함":"Reject/Withdraw Box",
 "반려/회수함":"Reject/Withdraw Box",
 "반려이력":"Reject Info.",
 "반려이력":"Reject Info.",
 "반려함":"반려함",
 "반려함":"반려함",
 "배부문서 ":"Distribution Doc.",
 "배부문서 ":"Distribution Doc.",
 "번호":"No.",
 "번호":"No.",
 "보안등급":"Doc. Security",
 "보안등급":"Doc. Security",
 "보존년한":"Doc. Retention Period",
 "보존년한":"Doc. Retention Period",
 "복사":"Copy",
 "복사":"Copy",
 "본문":"Content",
 "본문":"Content",
 "본문 확대":"Zoom-In",
 "본문 확대":"Zoom-In",
 "본문보기":"View Content",
 "본문보기":"View Content",
 "본문없음":"No text",
 "본문없음":"No text",
 "본문유형":"Form Type",
 "본문유형":"Form Type",
 "본문확대":"Expand",
 "본문확대":"Expand",
 "본사경비":"Head Office Expense",
 "본사경비":"Head Office Expense",
 "부결":"Not Approval",
 "부결":"Not Approval",
 "부서":"Department",
 "부서":"Department",
 "부서 정보 조회":"Department Information View",
 "부서 정보 조회":"Department Information View",
 "부서/사원명":"Dept/Person Name",
 "부서/사원명":"Dept/Person Name",
 "부서/팀":"Dept./Team",
 "부서/팀":"Dept./Team",
 "부서/현장":"Dept/Site",
 "부서/현장":"Dept/Site",
 "부서/현장명":"Dept/Proj. Name",
 "부서/현장명":"Dept/Proj. Name",
 "부서명":"Department Name",
 "부서명":"Department Name",
 "부서목록":"Depts",
 "부서목록":"Depts",
 "부서별":"by Department",
 "부서별":"by Department",
 "부서소속":"Department",
 "부서소속":"Department",
 "부서장":"Part Chief",
 "부서장":"Part Chief",
 "부서지정":"Department Selection",
 "부서지정":"Department Selection",
 "부서코드":"Department",
 "부서코드":"Department",
 "부서코드 팝업":"Department Code Popup",
 "부서코드 팝업":"Department Code Popup",
 "부서코드조회":"View/Query Department Code",
 "부서코드조회":"View/Query Department Code",
 "부서한":"Department",
 "부서한":"Department",
 "부서함":"Department",
 "부서함":"Department",
 "분류":"Type",
 "분류":"Type",
 "비밀":"Secret",
 "비밀":"Secret",
 "비밀번호":"Password ",
 "비밀번호":"Password ",
 "사내한":"Company",
 "사내한":"Company",
 "사용여부":"Use Y/N",
 "사용여부":"Use Y/N",
 "사용자":"User",
 "사용자":"User",
 "사용자 History":"User History",
 "사용자 History":"User History",
 "사용자 유형":"User Type",
 "사용자 유형":"User Type",
 "사용자 정보":"불필요",
 "사용자 정보":"불필요",
 "사용자 조회":"User View",
 "사용자 조회":"User View",
 "사용자 팝업":"User Popup",
 "사용자 팝업":"User Popup",
 "사용자ID":"User ID",
 "사용자ID":"User ID",
 "사용자관리":"User Management",
 "사용자관리":"User Management",
 "사용자구분":"User Type",
 "사용자구분":"User Type",
 "사용자명":"User Name",
 "사용자명":"User Name",
 "사용자목록":"User List",
 "사용자목록":"User List",
 "사용자지정":"User selection",
 "사용자지정":"User selection",
 "사원명":"Employee Name",
 "사원명":"Employee Name",
 "사전검토":"Pre Review",
 "사전검토":"Pre Review",
 "사전검토 출력여부":"Print Pre Reviewer Y/N",
 "사전검토 출력여부":"Print Pre Reviewer Y/N",
 "사전검토/회람자":"Pre Reviewer/Circular",
 "사전검토/회람자":"Pre Reviewer/Circular",
 "사전검토/회람정보":"Pre Reviewer/Circular Info",
 "사전검토/회람정보":"Pre Reviewer/Circular Info",
 "사전검토/회람정보조회":"PreReview/Circulation Info",
 "사전검토/회람정보조회":"PreReview/Circulation Info",
 "사전검토/회람지정":"Set Pre Reviewer/Circular",
 "사전검토/회람지정":"Set Pre Reviewer/Circular",
 "사전검토▼":"Pre Review▼",
 "사전검토▼":"Pre Review▼",
 "사전검토함":"Pre Review Box",
 "사전검토함":"Pre Review Box",
 "사전협의":"Pre Consultation",
 "사전협의":"Pre Consultation",
 "삭제":"Delete",
 "삭제":"Delete",
 "삭제▲":"Delete▲",
 "삭제▲":"Delete▲",
 "삭제▼":"Delete▼",
 "삭제▼":"Delete▼",
 "삭제함":"삭제함",
 "삭제함":"삭제함",
 "상세":"Detail",
 "상세":"Detail",
 "상세검색":"Advanced Search",
 "상세검색":"Advanced Search",
 "상세내용":"Detail",
 "상세내용":"Detail",
 "상세보기 팝업":"불필요",
 "상세보기 팝업":"불필요",
 "상신":"Draft",
 "상신":"Draft",
 "상신(전자결재)":"Request for Approval(Electronic Approval)",
 "상신(전자결재)":"Request for Approval(Electronic Approval)",
 "상신(전자결재) 처리 완료":"Request for Approval(Electronic Approval) Processing Complete",
 "상신(전자결재) 처리 완료":"Request for Approval(Electronic Approval) Processing Complete",
 "상신미리보기":"Draft Preview",
 "상신미리보기":"Draft Preview",
 "상신완료":"Draft completed",
 "상신완료":"Draft completed",
 "상신일자":"Draft Date",
 "상신일자":"Draft Date",
 "상신전":"Before report",
 "상신전":"Before report",
 "상신준비":"Report preparation",
 "상신준비":"Report preparation",
 "상신중":"Report in progress",
 "상신중":"Report in progress",
 "샘플":"Sample",
 "샘플":"Sample",
 "생성일":"생성일",
 "생성일":"생성일",
 "생성자":"Creator",
 "생성자":"Creator",
 "서식 다운로드":"Download Form File",
 "서식 다운로드":"Download Form File",
 "서식다운로드":"Download Form File",
 "서식다운로드":"Download Form File",
 "서식명":"Form Name",
 "서식명":"Form Name",
 "서식파일 목록":"Form File List",
 "서식파일 목록":"Form File List",
 "서식파일관리":"Form File Mgmt.",
 "서식파일관리":"Form File Mgmt.",
 "서식파일명":"Form File Name",
 "서식파일명":"Form File Name",
 "선택":"Select",
 "선택":"Select",
 "설명":"Description",
 "설명":"Description",
 "성명":"Name",
 "성명":"Name",
 "소속조직":"Departmnet Code",
 "소속조직":"Departmnet Code",
 "소속조직명":"Department Name",
 "소속조직명":"Department Name",
 "수신구분":"Receipt Type",
 "수신구분":"Receipt Type",
 "수신대기":"Waiting for receiving",
 "수신대기":"Waiting for receiving",
 "수신미열":"수신미열",
 "수신미열":"수신미열",
 "수신여부":"Receipt Flag",
 "수신여부":"Receipt Flag",
 "수신자":"Recipient",
 "수신자":"Recipient",
 "수신자명":"Recipient Name",
 "수신자명":"Recipient Name",
 "수신자목록":"Recipient List",
 "수신자목록":"Recipient List",
 "수신처":"Recipient",
 "수신처":"Recipient",
 "수신처 설정":"Recipient Info",
 "수신처 설정":"Recipient Info",
 "수신처 지정":"Recipient Y/N",
 "수신처 지정":"Recipient Y/N",
 "수신처 출력여부":"Print Recipient Y/N",
 "수신처 출력여부":"Print Recipient Y/N",
 "수신처지정":"Set Recipient",
 "수신처지정":"Set Recipient",
 "수신함":"Receive Box",
 "수신함":"Receive Box",
 "수신확인":"Confirm",
 "수신확인":"Confirm",
 "수정일":"Modify Dt",
 "수정일":"Modify Dt",
 "수정일시":"Modify Date",
 "수정일시":"Modify Date",
 "수정일자":"Date Updated",
 "수정일자":"Date Updated",
 "수정자":"Modify By",
 "수정자":"Modify By",
 "수정자ID":"Modify ID",
 "수정자ID":"Modify ID",
 "순번":"No.",
 "순번":"No.",
 "순서":"No.",
 "순서":"No.",
 "승인":"Approval",
 "승인":"Approval",
 "승인완료":"Approval Completed",
 "승인완료":"Approval Completed",
 "승인자":"Approbator",
 "승인자":"Approbator",
 "시스템":"System",
 "시스템":"System",
 "시스템 관리":"Sys Mng.",
 "시스템 관리":"Sys Mng.",
 "시스템관리":"System Management",
 "시스템관리":"System Management",
 "시스템구분":"System Classification",
 "시스템구분":"System Classification",
 "시스템명":"System Name",
 "시스템명":"System Name",
 "시작일":"Start Date",
 "시작일":"Start Date",
 "시작일자":"Start Date",
 "시작일자":"Start Date",
 "아니오":"N",
 "아니오":"N",
 "아래":"Down",
 "아래":"Down",
 "알림":"Notice",
 "알림":"Notice",
 "양식":"Form",
 "양식":"Form",
 "양식 매핑 관리":"Form Mapping Mgmt.",
 "양식 매핑 관리":"Form Mapping Mgmt.",
 "양식URL":"Form URL",
 "양식URL":"Form URL",
 "양식경로 또는 화면 URL":"Form Path or View URL",
 "양식경로 또는 화면 URL":"Form Path or View URL",
 "양식관리":"Form Mgmt",
 "양식관리":"Form Mgmt",
 "양식기본정보":"Basic Info",
 "양식기본정보":"Basic Info",
 "양식링크":"Form Link",
 "양식링크":"Form Link",
 "양식명":"Form Name",
 "양식명":"Form Name",
 "양식목록":"Form List",
 "양식목록":"Form List",
 "양식번호":"Form Number",
 "양식번호":"Form Number",
 "양식유형":"Form Type",
 "양식유형":"Form Type",
 "양식파일명":"Form File Name",
 "양식파일명":"Form File Name",
 "언어":"Lang",
 "언어":"Lang",
 "업무":"Biz.",
 "업무":"Biz.",
 "업무 유형":"Types of Work",
 "업무 유형":"Types of Work",
 "업무구분":"Biz. Class",
 "업무구분":"Biz. Class",
 "업무분류":"Biz. Type",
 "업무분류":"Biz. Type",
 "업무시스템":"Biz. System",
 "업무시스템":"Biz. System",
 "없음":"Empty",
 "없음":"Empty",
 "엑셀다운로드":"Download Exl",
 "엑셀다운로드":"Download Exl",
 "엑셀업로드":"Upload Exl.",
 "엑셀업로드":"Upload Exl.",
 "여기에 파일을 올려주세요":"Drag & Drop Files",
 "여기에 파일을 올려주세요":"Drag & Drop Files",
 "연결이 끊어졌습니다":"Connect Failed!",
 "연결이 끊어졌습니다":"Connect Failed!",
 "연동저장":"Interlocking save",
 "연동저장":"Interlocking save",
 "연동전":"Before interlocking",
 "연동전":"Before interlocking",
 "연동코드":"Form Code",
 "연동코드":"Form Code",
 "열람미결":"View undecided",
 "열람미결":"View undecided",
 "열람상태":"View Status",
 "열람상태":"View Status",
 "열람유형":"View Type",
 "열람유형":"View Type",
 "열람일시":"View Date",
 "열람일시":"View Date",
 "열람함":"Complete Box.",
 "열람함":"Complete Box.",
 "영구":"Archival Doc.",
 "영구":"Archival Doc.",
 "영문명":"English Name",
 "영문명":"English Name",
 "영문이름":"English Name",
 "영문이름":"English Name",
 "예":"Y",
 "예":"Y",
 "완결전":"Before completion",
 "완결전":"Before completion",
 "완결함":"Complete Box",
 "완결함":"Complete Box",
 "완결후":"After completion",
 "완결후":"After completion",
 "완료":"Completion",
 "완료":"Completion",
 "요청완료":"Request completed",
 "요청완료":"Request completed",
 "요청일시":"불필요",
 "요청일시":"불필요",
 "요청자":"Requestor",
 "요청자":"Requestor",
 "요청확인":"Request confirmation",
 "요청확인":"Request confirmation",
 "위":"Up",
 "위":"Up",
 "위원장":"Chairman",
 "위원장":"Chairman",
 "유":"Yes",
 "유":"Yes",
 "의견":"Opinion",
 "의견":"Opinion",
 "의견보기":"Opinion",
 "의견보기":"Opinion",
 "의견작성":"Opinion",
 "의견작성":"Opinion",
 "이관목록":"Transfer List",
 "이관목록":"Transfer List",
 "이단결재":"2'nd Approval",
 "이단결재":"2'nd Approval",
 "이단결재 본사상신":"2'nd Approval Draft",
 "이단결재 본사상신":"2'nd Approval Draft",
 "이단결재 수신함":"2'nd Approval Receive Box",
 "이단결재 수신함":"2'nd Approval Receive Box",
 "이단결재 수정":"2'nd Approval Modify",
 "이단결재 수정":"2'nd Approval Modify",
 "이단결재담당자":"Person in charge of double approval",
 "이단결재담당자":"Person in charge of double approval",
 "이단결재대기":"Waiting for double approval",
 "이단결재대기":"Waiting for double approval",
 "이단결재수신함":"2'nd Approval Receive Box",
 "이단결재수신함":"2'nd Approval Receive Box",
 "이단결재정보":"2'nd Level Approval",
 "이단결재정보":"2'nd Level Approval",
 "이단결재함":"2'nd Sign Box",
 "이단결재함":"2'nd Sign Box",
 "이동":"Move",
 "이동":"Move",
 "이름":"Name",
 "이름":"Name",
 "이메일사용여부":"E-Mail Status",
 "이메일사용여부":"E-Mail Status",
 "이메일주소":"E-mail",
 "이메일주소":"E-mail",
 "인쇄":"Print",
 "인쇄":"Print",
 "인쇄 항목 설정":"Print Option",
 "인쇄 항목 설정":"Print Option",
 "인터페이스 사용여부":"Interface Use Y/N",
 "인터페이스 사용여부":"Interface Use Y/N",
 "인터페이스로그":"Interface Log",
 "인터페이스로그":"Interface Log",
 "일괄결재":"All Approval",
 "일괄결재":"All Approval",
 "일반":"General",
 "일반":"General",
 "일반문서":"General Document",
 "일반문서":"General Document",
 "임시":"Temporary",
 "임시":"Temporary",
 "임시저장":"Save Box",
 "임시저장":"Save Box",
 "임시저장함":"Save Box",
 "임시저장함":"Save Box",
 "작성완료":"Completed",
 "작성완료":"Completed",
 "작성일자":"Date Writed",
 "작성일자":"Date Writed",
 "작성자":"Creator",
 "작성자":"Creator",
 "작성자 부서":"Creator Department",
 "작성자 부서":"Creator Department",
 "작성조직":"Responsibility",
 "작성조직":"Responsibility",
 "작성중":"Working",
 "작성중":"Working",
 "작성함":"Form Box",
 "작성함":"Form Box",
 "재기안":"Redraft",
 "재기안":"Redraft",
 "재심의":"Re-Deliberation",
 "재심의":"Re-Deliberation",
 "저장":"Save",
 "저장":"Save",
 "저장일":"Create Date",
 "저장일":"Create Date",
 "전결":"Abitrary Appr",
 "전결":"Abitrary Appr",
 "전결규정":"Abitrary Appr Rule",
 "전결규정":"Abitrary Appr Rule",
 "전결규정관리":"Arbitrary Appr Rule Mgmt.",
 "전결규정관리":"Arbitrary Appr Rule Mgmt.",
 "전결규정적용":"Abitrary Appr Rule Y/N",
 "전결규정적용":"Abitrary Appr Rule Y/N",
 "전결규정조회":"Arbitrary Appr Rule",
 "전결규정조회":"Arbitrary Appr Rule",
 "전결규정지정":"Abitrary Appr Rule",
 "전결규정지정":"Abitrary Appr Rule",
 "전결자":"Abitrary Appr",
 "전결자":"Abitrary Appr",
 "전결코드":"Abitrary Appr Code",
 "전결코드":"Abitrary Appr Code",
 "전사":"All",
 "전사":"All",
 "전자증빙":"Digital Evidence",
 "전자증빙":"Digital Evidence",
 "전자증빙 ":"Electronic Evidence",
 "전자증빙 ":"Electronic Evidence",
 "점검":"Notice",
 "점검":"Notice",
 "제목":"Title",
 "제목":"Title",
 "제목:":"Title",
 "제목:":"Title",
 "조건1":"Condition1",
 "조건1":"Condition1",
 "조건2":"조건2",
 "조건2":"조건2",
 "조건3":"조건3",
 "조건3":"조건3",
 "조건4":"조건4",
 "조건4":"조건4",
 "조건부 승인":"Conditional Approval",
 "조건부 승인":"Conditional Approval",
 "조건부 승인(재품의)":"Conditional Approval(Redraft)",
 "조건부 승인(재품의)":"Conditional Approval(Redraft)",
 "조직":"Organization ",
 "조직":"Organization ",
 "조직/사용자 조회":"Organization/User View",
 "조직/사용자 조회":"Organization/User View",
 "조직/사용자 팝업":"Organization/User Popup",
 "조직/사용자 팝업":"Organization/User Popup",
 "조직관리":"Organization Management",
 "조직관리":"Organization Management",
 "조직명":"Organization Name",
 "조직명":"Organization Name",
 "조회":"Search",
 "조회":"Search",
 "종료일":"End Date",
 "종료일":"End Date",
 "종료일자":"End Date",
 "종료일자":"End Date",
 "주관부서":"Incharge Dept",
 "주관부서":"Incharge Dept",
 "지정된사용자":"Selected user",
 "지정된사용자":"Selected user",
 "지정부서":"Selected Department",
 "지정부서":"Selected Department",
 "직급":"Grade",
 "직급":"Grade",
 "직무":"Duty",
 "직무":"Duty",
 "직무/직책":"Duty/Position",
 "직무/직책":"Duty/Position",
 "직무명":"Duty Name",
 "직무명":"Duty Name",
 "직무명1":"Duty 1",
 "직무명1":"Duty 1",
 "직무명2":"Duty 2",
 "직무명2":"Duty 2",
 "직무명3":"Duty 3",
 "직무명3":"Duty 3",
 "직무명4":"Duty 4",
 "직무명4":"Duty 4",
 "직원목록":"Persons",
 "직원목록":"Persons",
 "직원조회":"Employee View",
 "직원조회":"Employee View",
 "직위":"Title",
 "직위":"Title",
 "직위명":"Title Name",
 "직위명":"Title Name",
 "직종":"Occupation",
 "직종":"Occupation",
 "직종명":"Occupation Name",
 "직종명":"Occupation Name",
 "직책":"Job Position",
 "직책":"Job Position",
 "직책/직무":"Position/Duty",
 "직책/직무":"Position/Duty",
 "직책/직무명":"Position/Duty",
 "직책/직무명":"Position/Duty",
 "직책명":"Job Position Name",
 "직책명":"Job Position Name",
 "직함명":"불필요",
 "직함명":"불필요",
 "진행":"ING",
 "진행":"ING",
 "진행함":"Progress Box",
 "진행함":"Progress Box",
 "처리상태":"불필요",
 "처리상태":"불필요",
 "첨부 문서":"Attachment",
 "첨부 문서":"Attachment",
 "첨부된 파일이 없습니다.":"There are no files attached.",
 "첨부된 파일이 없습니다.":"There are no files attached.",
 "첨부문서":"Attachment",
 "첨부문서":"Attachment",
 "첨부문서 목록":"Attachment List",
 "첨부문서 목록":"Attachment List",
 "첨부문서 추가":"Attach Doc.",
 "첨부문서 추가":"Attach Doc.",
 "첨부문서 출력여부":"Print Doc Attachment Y/N",
 "첨부문서 출력여부":"Print Doc Attachment Y/N",
 "첨부문서지정":"Doc. Attach",
 "첨부문서지정":"Doc. Attach",
 "첨부의견":"Opinion",
 "첨부의견":"Opinion",
 "첨부파일":"Attached File",
 "첨부파일":"Attached File",
 "첨부파일 단건":"Single Attachment",
 "첨부파일 단건":"Single Attachment",
 "첨부파일 목록":"Attached File List",
 "첨부파일 목록":"Attached File List",
 "첨부파일 보기":"Preview",
 "첨부파일 보기":"Preview",
 "첨부파일 출력여부":"Print Attachment Y/N",
 "첨부파일 출력여부":"Print Attachment Y/N",
 "첨부파일명":"Attached File Name",
 "첨부파일명":"Attached File Name",
 "초기화":"Initialize",
 "초기화":"Initialize",
 "최근 기안 양식":"Recent Draft Form",
 "최근 기안 양식":"Recent Draft Form",
 "최종요청자":"Requestor",
 "최종요청자":"Requestor",
 "추가":"Add",
 "추가":"Add",
 "취소":"Cancel",
 "취소":"Cancel",
 "콜백 재전송":"Callback Re-send",
 "콜백 재전송":"Callback Re-send",
 "쿼리":"Query",
 "쿼리":"Query",
 "투자심의":"Investment Deliberation",
 "투자심의":"Investment Deliberation",
 "투자심의 결과":"Investment Deliberation Result",
 "투자심의 결과":"Investment Deliberation Result",
 "투자심의함":"Investment Deliberation Box",
 "투자심의함":"Investment Deliberation Box",
 "팀장":"Team leader",
 "팀장":"Team leader",
 "팀장결재":"Approval of team leader",
 "팀장결재":"Approval of team leader",
 "팀장결재대기":"Waiting for approval of team leader",
 "팀장결재대기":"Waiting for approval of team leader",
 "팀장결재중":"Under approval of team leader",
 "팀장결재중":"Under approval of team leader",
 "팀장반려":"Team leader rejection",
 "팀장반려":"Team leader rejection",
 "파일 목록":"File List",
 "파일 목록":"File List",
 "파일 수정":"Change",
 "파일 수정":"Change",
 "파일 첨부":"File Attachment",
 "파일 첨부":"File Attachment",
 "파일경로(파일명 포함)":"불필요",
 "파일경로(파일명 포함)":"불필요",
 "파일다운로드":"불필요",
 "파일다운로드":"불필요",
 "파일명":"File Name",
 "파일명":"File Name",
 "파일삭제":"Delete",
 "파일삭제":"Delete",
 "파일선택":"Open",
 "파일선택":"Open",
 "파일설명":"File Description",
 "파일설명":"File Description",
 "파일업로드":"불필요",
 "파일업로드":"불필요",
 "파일열기":"File Open",
 "파일열기":"File Open",
 "파일유형":"File Type",
 "파일유형":"File Type",
 "파일을 다운로드하고 있습니다":"Downloading Files",
 "파일을 다운로드하고 있습니다":"Downloading Files",
 "파일을 업로드하고 있습니다":"Uploading Files",
 "파일을 업로드하고 있습니다":"Uploading Files",
 "파일첨부":"File Attachment",
 "파일첨부":"File Attachment",
 "파일첨부 팝업":"File Attachment Popup",
 "파일첨부 팝업":"File Attachment Popup",
 "파일첨부ID":"File Attachment ID",
 "파일첨부ID":"File Attachment ID",
 "파일추가":"Add",
 "파일추가":"Add",
 "파일크기":"File Size",
 "파일크기":"File Size",
 "파일크기(byte)":"File Size",
 "파일크기(byte)":"File Size",
 "팝업":"Pop-Up",
 "팝업":"Pop-Up",
 "편집":"Edit",
 "편집":"Edit",
 "편집 이력":"Edit History",
 "편집 이력":"Edit History",
 "편집내용":"Comment",
 "편집내용":"Comment",
 "편집이력조회":"Edit History",
 "편집이력조회":"Edit History",
 "편집일":"Edit Date",
 "편집일":"Edit Date",
 "편집자":"Editor",
 "편집자":"Editor",
 "포스트 잇":"Post-It",
 "포스트 잇":"Post-It",
 "행":"Row",
 "행":"Row",
 "행삭제":"Del. Row",
 "행삭제":"Del. Row",
 "행추가":"Ins. Row",
 "행추가":"Ins. Row",
 "현장":"Site",
 "현장":"Site",
 "현장 명":"Site Name",
 "현장 명":"Site Name",
 "협의▼":"Assist▼",
 "협의▼":"Assist▼",
 "협의대상":"Direct Execution Statement",
 "협의대상":"Direct Execution Statement",
 "협의반려":"Negotiation rejection",
 "협의반려":"Negotiation rejection",
 "협의완료":"Negotiation completed",
 "협의완료":"Negotiation completed",
 "협의요청":"Negotiation request",
 "협의요청":"Negotiation request",
 "협의자":"Negotiator",
 "협의자":"Negotiator",
 "협의중":"Under negotiation",
 "협의중":"Under negotiation",
 "협의팀 승인":"Consultation Team Approval",
 "협의팀 승인":"Consultation Team Approval",
 "협의팀검토":"Negotiation team review",
 "협의팀검토":"Negotiation team review",
 "협의팀반려":"Negotiation team rejection",
 "협의팀반려":"Negotiation team rejection",
 "확인":"Confirm",
 "확인":"Confirm",
 "환경설정":"Setting",
 "환경설정":"Setting",
 "회람":"Circular",
 "회람":"Circular",
 "회람 이력":"Internal Approval Status",
 "회람 이력":"Internal Approval Status",
 "회람▼":"Circular▼",
 "회람▼":"Circular▼",
 "회람대기함":"Circular waiting box",
 "회람대기함":"Circular waiting box",
 "회람문서열람":"Circulation Box",
 "회람문서열람":"Circulation Box",
 "회람상태":"Status",
 "회람상태":"Status",
 "회람완료함":"Circular completion box",
 "회람완료함":"Circular completion box",
 "회람유형":"Circuration Type",
 "회람유형":"Circuration Type",
 "회람일시":"Date",
 "회람일시":"Date",
 "회람자":"Circulator",
 "회람자":"Circulator",
 "회람자 정보":"Circulators",
 "회람자 정보":"Circulators",
 "회람자 지정":"Circulator",
 "회람자 지정":"Circulator",
 "회람자 출력여부":"Print Circular Y/N",
 "회람자 출력여부":"Print Circular Y/N",
 "회람자변경":"Circulator",
 "회람자변경":"Circulator",
 "회람자지정":"Circulator",
 "회람자지정":"Circulator",
 "회람정보":"Circulation Info",
 "회람정보":"Circulation Info",
 "회람정보조회":"Circulation Info",
 "회람정보조회":"Circulation Info",
 "회람지정":"Add Circular",
 "회람지정":"Add Circular",
 "회람함":"Circulation Box",
 "회람함":"Circulation Box",
 "회수":"Withdraw",
 "회수":"Withdraw",
 "회수함":"Collection box",
 "회수함":"Collection box",
 "회신":"DRF",
 "회신":"DRF"

}

